# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:

    branches: 
      - testing_branch
  pull_request:
    branches: 
      - testing_branch
  workflow_dispatch:
    branches: 
      - testing_branch

jobs:
  build:
    name: Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

        pip install -e .[dev]
        
    - name: Test with pytest
      run: |
        pytest
